<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartUserManagement.Business\SmartUserManagement.Business.csproj" />
    <ProjectReference Include="..\SmartUserManagement.Domain\SmartUserManagement.Domain.csproj" />
    <ProjectReference Include="..\SmartUserManagement.Repository\SmartUserManagement.Repository.csproj" />
  </ItemGroup>

</Project>
